"""add completed_at to todos

Revision ID: 022645b2e444
Revises: 7d1461ba153c
Create Date: 2026-02-12 13:31:35.340113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022645b2e444'
down_revision: Union[str, Sequence[str], None] = '7d1461ba153c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed_at')
    # ### end Alembic commands ###
