"""add whatsapp notifications fields

Revision ID: 0a19600cfd38
Revises: 022645b2e444
Create Date: 2026-03-02 13:01:32.840489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a19600cfd38'
down_revision: Union[str, Sequence[str], None] = '022645b2e444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('task_time', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('todos', 'notification_enabled')
    op.drop_column('todos', 'task_time')
    # ### end Alembic commands ###
