"""add whatsapp notifications fields

Revision ID: 0a19600cfd38
Revises: 022645b2e444
Create Date: 2026-03-02 13:01:32.840489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a19600cfd38'
down_revision: Union[str, Sequence[str], None] = '022645b2e444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    # Check todos table columns
    todos_columns = [col['name'] for col in inspector.get_columns('todos')]

    if 'task_time' not in todos_columns:
        op.add_column('todos', sa.Column('task_time', sa.DateTime(), nullable=True))
        print("✅ Added task_time column to todos table")
    else:
        print("ℹ️  task_time column already exists, skipping")

    if 'notification_enabled' not in todos_columns:
        op.add_column('todos', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
        print("✅ Added notification_enabled column to todos table")
    else:
        print("ℹ️  notification_enabled column already exists, skipping")

    # Check users table columns
    users_columns = [col['name'] for col in inspector.get_columns('users')]

    if 'phone_number' not in users_columns:
        op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
        print("✅ Added phone_number column to users table")
    else:
        print("ℹ️  phone_number column already exists, skipping")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('todos', 'notification_enabled')
    op.drop_column('todos', 'task_time')
    # ### end Alembic commands ###
