"""add created_at to todos

Revision ID: 7d1461ba153c
Revises: 4db26f46d94f
Create Date: 2026-02-12 12:48:37.956617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1461ba153c'
down_revision: Union[str, Sequence[str], None] = '4db26f46d94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table exists first
    from sqlalchemy import inspect
    from sqlalchemy.engine import reflection

    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check if todos table exists
    if 'todos' not in inspector.get_table_names():
        print("⚠️  todos table doesn't exist yet, skipping created_at column addition")
        return
    
    columns = [col['name'] for col in inspector.get_columns('todos')]

    if 'created_at' not in columns:
        # Add column as nullable first
        op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
        # Set default value for existing rows
        op.execute("UPDATE todos SET created_at = NOW() WHERE created_at IS NULL")
        # Make it not nullable
        op.alter_column('todos', 'created_at',
                        existing_type=sa.DateTime(),
                        nullable=False)
        print("✅ Added created_at column to todos table")
    else:
        print("ℹ️  created_at column already exists, skipping")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
